### PR TITLE
refactor royale

### PR DESCRIPTION
**Pull request by drahnr**

### CODE REVIEW

**Comment by bytesnake** [comment]
**microphone drop**, wanna talk about it? xD would be actually interested to know what your using if for? :)

**Comment by drahnr** [comment]
I started writing a mdbook but realized I needed formulae and code in the same document AND all kinds mermaid graphs. This was a good starting point :)

So bumped all the dependencies and added some detection improvements for `$` and `$$` in conjunction with inline code segments and disabled the code part and replaced that with some pulldown-cmark based logic

I usually don't bother to try contribute to projects that haven't seen a commit in more than 2 years, usually the author moved on

I'd be happy collaborate though :)

**Comment by bytesnake** [comment]
your awesome, thanks!

> I started writing a mdbook but realized I needed formulae and code in the same document AND all kinds mermaid graphs. 

my initial motive came out of interest for note taking with mdbook, but found it soon too linear and distracting in my vim workflow. Writing course material or documentation on scientific crates may be interesting but haven't come to much of that

> I usually don't bother to try contribute to projects that haven't seen a commit in more than 2 years, usually the author moved on

like many personal projects they die in silence

> I'd be happy collaborate though :)

how would you like to proceed, would you get any benefit in reviewing this? Should we move it into a github organization? I will not come to review this week, perhaps next but can't promise.

**Comment by drahnr** [comment]
A org would be nice, but only if you have the capacity and time to work on it. Otherwise, I'd say I just push along. I have a very specific use case I need to make work, particularly around the tripplet of github.com/drahnr/mdbook-tectonic | html | mermaid - I am not entirely sure this is generally useful outside my specific usecase.

**Comment by drahnr** [comment]
@bytesnake I'd be happy to have you as a reviewer, I refactored a few crates that I needed and put them under https://github.com/drahnr/fancybook don't feel obligated though, there is a life away from the screen

**Comment by bytesnake** [comment]
probably won't happen this week but I will keep an eye on it. I focus my free time currently on the rust compiler fork for enzyme and it's a time sink recently (but a very educational one :D)

**Pull request closed without merging**
